// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cadastroDePacientes.Ressource
{
    /// <summary>
    /// tabela de registro de pacientes
    /// </summary>
    public partial class paciente
    {
        public paciente()
        {
            presenca = new HashSet<presenca>();
            servicos = new HashSet<servicos>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int paciente_id { get; set; }
        [Required]
        [StringLength(60)]
        public string nome { get; set; }
        [Required]
        [StringLength(12)]
        public string sexo { get; set; }
        [Required]
        [StringLength(8)]
        public string situacaoderua { get; set; }
        public DateOnly datadenascimento { get; set; }
        [Required]
        [StringLength(60)]
        public string cns { get; set; }
        [Required]
        [StringLength(60)]
        public string email { get; set; }
        [Required]
        [StringLength(20)]
        public string telefone { get; set; }
        [Required]
        [StringLength(20)]
        public string telefone2 { get; set; }
        [Required]
        [StringLength(30)]
        public string escolaridade { get; set; }
        [Required]
        [StringLength(8)]
        public string cid { get; set; }
        [Required]
        [StringLength(5)]
        public string tentativadesuicidio { get; set; }
        [Required]
        [StringLength(60)]
        public string nomedamae { get; set; }
        [Required]
        [StringLength(80)]
        public string endereco { get; set; }
        [Required]
        [StringLength(80)]
        public string endereco2 { get; set; }
        public DateOnly dataderegistro { get; set; }
        [Required]
        [StringLength(60)]
        public string tr { get; set; }
        [Required]
        [StringLength(60)]
        public string ubsreferencia { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime comparecimento { get; set; }
        [Required]
        [StringLength(12)]
        public string ativoinativo { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string grupos { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string comorbidade { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string beneficio { get; set; }
        [Required]
        [StringLength(60)]
        public string rede { get; set; }
        public DateOnly ultimapresenca { get; set; }
        [Required]
        [StringLength(40)]
        public string atendimentotr { get; set; }
        [Required]
        [StringLength(40)]
        public string vd { get; set; }
        [Precision(10, 0)]
        public decimal numeroprontuario { get; set; }
        [Required]
        [StringLength(23)]
        public string responsavel { get; set; }
        [Required]
        [StringLength(23)]
        public string cpf { get; set; }
        [Required]
        [StringLength(22)]
        public string rg { get; set; }
        [Required]
        [StringLength(22)]
        public string estadocivil { get; set; }
        [Required]
        [StringLength(22)]
        public string cep { get; set; }
        [Required]
        [StringLength(22)]
        public string encaminhamentoporvia { get; set; }
        [Required]
        [StringLength(10)]
        public string demandaespontanea { get; set; }
        [Required]
        [StringLength(22)]
        public string nacionalidade { get; set; }
        [Required]
        [StringLength(22)]
        public string naturalidade { get; set; }
        [Required]
        [StringLength(40)]
        public string bairro { get; set; }
        [Required]
        [StringLength(40)]
        public string cidade { get; set; }
        [Required]
        [StringLength(120)]
        public string acompanhante { get; set; }

        [InverseProperty("paciente")]
        public virtual ICollection<presenca> presenca { get; set; }
        [InverseProperty("paciente")]
        public virtual ICollection<servicos> servicos { get; set; }
    }
}