// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cadastroDePacientes.Ressource
{
    [Index("paciente_id", Name = "paciente_id")]
    public partial class presenca
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int id_presenca { get; set; }
        public DateOnly datapresenca { get; set; }
        [Column(TypeName = "int(111)")]
        public int paciente_id { get; set; }

        [ForeignKey("paciente_id")]
        [InverseProperty("presenca")]
        public virtual paciente paciente { get; set; }
    }
}