// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace cadastroDePacientes.Ressource
{
    [Index("paciente_id", Name = "paciente_id")]
    public partial class servicos
    {
        [Key]
        [Column(TypeName = "int(200)")]
        public int id_servicos { get; set; }
        [Required]
        [StringLength(30)]
        public string servico { get; set; }
        [Column(TypeName = "int(200)")]
        public int paciente_id { get; set; }
        public DateOnly dataservico { get; set; }
        [Required]
        [StringLength(40)]
        public string nomecolaborador { get; set; }

        [ForeignKey("paciente_id")]
        [InverseProperty("servicos")]
        public virtual paciente paciente { get; set; }
    }
}